Message.create!(text: 'My first text!')
Message.create!(text: 'My second text!')
Message.create!(text: 'My thrid text!')
Message.create!(text: 'My fourth text!')
Message.create!(text: 'My fifth text!')
